# https://medium.com/@shakyShane/laravel-docker-part-1-setup-for-development-e3daaefaf3c?token=i6JtSuvpAr7sbCvu
version: '2'
services:
  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 80:80